### ISSUE TITLE
DNS resolution fails for some clients

### ISSUE THREAD

**Issue by vlfig** [zliu41/zliu41.github.io#1]
Hi,

Can't resolve your free.cofree.io domain. It may be restricted to Linux clients (inferred from a very small sample).

It may also — I speculate — have something to do with the DNS setup
```
free.cofree.io.         3599    IN      CNAME   https://zliu41.github.io.
https://zliu41.github.io. 3599  IN      A       185.199.108.153
https://zliu41.github.io. 3599  IN      A       185.199.111.153
https://zliu41.github.io. 3599  IN      A       185.199.109.153
https://zliu41.github.io. 3599  IN      A       185.199.110.153
```
where two things stand out:
1. the cname isn't just a domain, it contains the protocol/scheme part.
2. `zliu41.github.io` 301 redirects to `free.cofree.io`, which _feels_ to be the wrong direction as the former is the canonical.

```
curl: (6) Could not resolve host: free.cofree.io
➜  ~ curl https://free.cofree.io/                        
curl: (6) Could not resolve host: free.cofree.io
➜  ~ curl https://zliu41.github.io/                        
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
➜  ~ curl -L https://zliu41.github.io/                     
curl: (6) Could not resolve host: free.cofree.io
```

**Comment by zliu41** [comment]
@vlfig Thanks for alerting me! I somehow missed the original notification and only just saw this.

I've removed `https` from the CNAME; it should work now.

**Comment by vlfig** [comment]
can confirm :-)
